Fix parsing of fields containing double quotes.
## Issue

Import choke with error:

	_csv.Error: '	<tab>' expected after '"'

(between the first pair of quotes, it was actually a tab character,
not the string <tab>)

The line cauding the error was certainly:

<tab>73032<tab>20180300<tab>"Kholle" de physique<tab><tab>Lycée Sainte-Geneviève<tab><tab><tab><tab><tab><tab><tab><tab><tab><tab><tab><tab><tab><tab>02/09/2019<tab>02/03/2020<tab><tab>0<tab>0<tab>0

## Analysis

* We instructed the parser to expect double-quote-quoted fields.
* The line above doesn't conform to this because after the supposedly
  field-closing double-quote, there is a space, actually the field
  continues.
* We offer as a solution to tell the Python csv importer to actually not
  expect any quoting character.
* It is implemented with this commit.